version: 2

project_name: terraform-provider-ciscosecureconnect

builds:
  - id: provider
    main: .
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

archives:
  - id: archive
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

signs:
  - id: gpg
    artifacts: checksum
    cmd: gpg
    args:
      - --batch
      - --yes
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.GPG_PASSPHRASE }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  # repo-level release options (NOT nested under github)
  ids: []                 # empty = use all archives
  draft: false            # <-- moved here (release-level)
  replace_existing_draft: false
  use_existing_draft: false
  prerelease: auto        # true/false/auto - set as you need
  make_latest: true
  mode: append
  disable: false
  skip_upload: false
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

  # SCM specific config
  github:
    owner: Cashy89
    name: terraform-provider-ciscosecureconnect
    # github.* only contains owner/name and other github-specific options,
    # but NOT draft/prerelease (those live at the release: level above).

changelog:
  disable: true   # replace old `skip: true` with `disable: true`

# other optional settings...
