project_name: terraform-provider-ciscosecureconnect

builds:
  - id: provider
    main: ./main.go               # adjust if your entrypoint is different
    binary: terraform-provider-ciscosecureconnect
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    format: tar.gz
    files:
      - terraform-registry-manifest.json
      - README.md
      - LICENSE

signs:
  - id: gpg
    cmd: gpg
    args:
      - --batch
      - --yes
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.GPG_PASSPHRASE }}"
      - --output
      - "{{ .ArtifactPath }}.sig"
      - --detach-sign
      - "{{ .ArtifactPath }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Cashy89
    name: terraform-provider-ciscosecureconnect
    draft: false
    prerelease: false

changelog:
  skip: true
